services:
  backend:
    image: agent111/xslt-web_frontend-backend:latest
    ports:
      - "3000:3000"  # Expose backend port within the container network
    networks:
      - app-network

  frontend:
    image: nginx:latest
    ports:
      - "5173:80"  # Map host port 5173 to container port 80
    volumes:
      - ./XSLT-Web_frontend/dist:/usr/share/nginx/html
    networks:
      - app-network
    command: /bin/sh -c "chmod -R 755 /usr/share/nginx/html && nginx -g 'daemon off;'"

networks:
  app-network:
    driver: bridge
